---
language: node_js
node_js:
  - 6.9.2

sudo: false

cache:
  directories:
    - bower_components
    - node_modules

before_install:
  - npm config set spin false
  - npm install -g npm@^2

install:
  - npm install -g phantomjs-prebuilt@2.1.14
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test
