ember: &defaults
  image: randallmorey/sass-ember-cli
  command: ['server', '--watcher', 'polling']
  volumes:
    - .:/ember-cli-app
  ports:
    - 4200:4200
    - 49152:49152
sh:
  <<: *defaults
  entrypoint: '/bin/sh'
  command: ''
npm:
  <<: *defaults
  entrypoint: ['/usr/bin/npm']
  command: ['--help']
bower:
  <<: *defaults
  entrypoint: ['/usr/bin/bower', '--allow-root', '--config.interactive=false']
  command: ['--help']
build_production:
  <<: *defaults
  entrypoint: ['/bin/sh']
  command: '-c "rm -rf node_modules bower_components && npm install && bower install --allow-root && ember build --environment production"'
