ember: &defaults
  image: randallmorey/ember-cli-native-support:2.4.0
  command: ['server', '--watcher', 'polling']
  volumes:
    - .:/ember-cli-app
  ports:
    - 4200:4200
    - 49152:49152
sh:
  <<: *defaults
  entrypoint: ['/bin/sh']
  command: ''
npm:
  <<: *defaults
  entrypoint: ['/usr/bin/npm']
  command: ['--help']
bower:
  <<: *defaults
  entrypoint: ['/usr/bin/bower', '--allow-root', '--config.interactive=false']
  command: ['--help']
build_production:
  <<: *defaults
  volumes:
    - .:/ember-cli-app
    - $GATEWAY_UI_DEST:/ember-cli-app/dist
  entrypoint: ['/bin/sh']
  command: '-c "npm install && bower install --allow-root --config.interactive=false && ember build --environment production"'
