`import RemoteEndpointQueryParameterFormController from 'gateway/controllers/remote-endpoint-query-parameter/form'`

RemoteEndpointQueryParameterInlineFormController = RemoteEndpointQueryParameterFormController.extend()

`export default RemoteEndpointQueryParameterInlineFormController`
